server:
  port: 8089
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 10.68.244.130
    port: 5672
    username: test
    password: 123456
    publisher-confirms: true  #手动确认
    publisher-returns: true
#    virtualHost: /        #虚拟机路径
    template:
      mandatory: true
      retry:
        enabled: true       #重试
        max-attempts: 2
        initial-interval: 1000
        max-interval: 5000
        multiplier: 2
#    requestedHeartbeat: 4

redis:
  url: redis://user:10.68.244.165:6379
  timeout: 5s
  lettuce:
    pool:
      max-active: 1000
      max-idle: 20
      min-idle: 0
      max-wait: 5s
